USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'QuanLyCuaHangGiaDung')
BEGIN
    ALTER DATABASE QuanLyCuaHangGiaDung SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QuanLyCuaHangGiaDung;
END
GO

CREATE DATABASE QuanLyCuaHangGiaDung;
GO

USE QuanLyCuaHangGiaDung;
GO

---------------------------------------------------------
-- 1. TẠO CẤU TRÚC BẢNG
---------------------------------------------------------
CREATE TABLE CON_NGUOI (
    ID_CN     INT PRIMARY KEY IDENTITY(1,1),
    TEN       NVARCHAR(100) NOT NULL,
    DOB       DATE,
    GIOI_TINH NVARCHAR(10),
    SDT       VARCHAR(15),
    EMAIL     VARCHAR(100)
);

-- Bảng quy tắc xếp hạng khách hàng
-- Quy tắc tích điểm: cứ 100.000đ chi tiêu => +1 điểm
-- 4 hạng: Thân thiết | Bạc | Vàng | Kim cương (KHÔNG có hạng Đồng)
CREATE TABLE HANG_KH (
    HANG     NVARCHAR(50) PRIMARY KEY,
    DIEM_MIN INT NOT NULL,
    DIEM_MAX INT NOT NULL,
    MO_TA    NVARCHAR(200)
);

-- Lương cơ bản là mức lương MỖI CA, nhân với số ca để ra lương tháng
-- Lương thực nhận = LUONG_CO_BAN x SO_CA_LAM + THUONG
-- 1 ngày có 3 ca: Sáng, Chiều, Tối
CREATE TABLE CHUC_VU (
    MA_CV        VARCHAR(10) PRIMARY KEY,
    TEN_CV       NVARCHAR(100),
    LUONG_CO_BAN DECIMAL(18,2) DEFAULT 0  -- Lương mỗi ca
);

CREATE TABLE CA_LAM (
    MA_CA     VARCHAR(10) PRIMARY KEY,
    THOI_GIAN NVARCHAR(50),
    NGAY      DATE
);

CREATE TABLE NHA_CUNG_CAP (
    MA_NCC  VARCHAR(10) PRIMARY KEY,
    TEN     NVARCHAR(100),
    SDT     VARCHAR(15),
    DIA_CHI NVARCHAR(200)
);

CREATE TABLE NHAN_VIEN (
    ID_NV      INT PRIMARY KEY,
    TRANG_THAI NVARCHAR(50),
    MA_CV      VARCHAR(10),
    ID_QL      INT,
    CONSTRAINT FK_NV_CN FOREIGN KEY (ID_NV) REFERENCES CON_NGUOI(ID_CN),
    CONSTRAINT FK_NV_CV FOREIGN KEY (MA_CV)  REFERENCES CHUC_VU(MA_CV),
    CONSTRAINT FK_NV_QL FOREIGN KEY (ID_QL)  REFERENCES NHAN_VIEN(ID_NV)
);

CREATE TABLE KHACH_HANG (
    ID_KH INT PRIMARY KEY,
    KHTT  NVARCHAR(50) DEFAULT N'Thân thiết',
    DIEM  INT DEFAULT 0,
    CONSTRAINT FK_KH_CN   FOREIGN KEY (ID_KH) REFERENCES CON_NGUOI(ID_CN),
    CONSTRAINT FK_KH_HANG FOREIGN KEY (KHTT)  REFERENCES HANG_KH(HANG)
);

CREATE TABLE HANG_HOA (
    MA_HH       VARCHAR(10) PRIMARY KEY,
    TEN_HH      NVARCHAR(200),
    SO_LUONG    INT DEFAULT 0,
    GIA         DECIMAL(18,2) CHECK (GIA >= 0),
    LOAI_HH     NVARCHAR(100),
    NGAY_NHAP   DATE,
    HAN_SU_DUNG DATE,
    MA_NCC      VARCHAR(10),
    CONSTRAINT FK_HH_NCC FOREIGN KEY (MA_NCC) REFERENCES NHA_CUNG_CAP(MA_NCC)
);

-- LUONG_THUC_NHAN = LUONG_CO_BAN (mỗi ca) x SO_CA_LAM + THUONG
CREATE TABLE LUONG (
    ID_NV     INT PRIMARY KEY,
    THUONG    DECIMAL(18,2) DEFAULT 0,
    SO_CA_LAM INT DEFAULT 0,
    MA_CV     VARCHAR(10),
    CONSTRAINT FK_LUONG_NV FOREIGN KEY (ID_NV) REFERENCES NHAN_VIEN(ID_NV),
    CONSTRAINT FK_LUONG_CV FOREIGN KEY (MA_CV) REFERENCES CHUC_VU(MA_CV)
);

CREATE TABLE CHAM_CONG (
    MA_CA VARCHAR(10),
    ID_NV INT,
    PRIMARY KEY (MA_CA, ID_NV),
    CONSTRAINT FK_CC_CA FOREIGN KEY (MA_CA) REFERENCES CA_LAM(MA_CA),
    CONSTRAINT FK_CC_NV FOREIGN KEY (ID_NV) REFERENCES NHAN_VIEN(ID_NV)
);

CREATE TABLE HOA_DON (
    MA_HD     VARCHAR(10) PRIMARY KEY,
    THOI_GIAN DATETIME DEFAULT GETDATE(),
    TONG_TIEN DECIMAL(18,2) DEFAULT 0,
    ID_NV     INT,
    ID_KH     INT,
    MA_CA     VARCHAR(10),
    CONSTRAINT FK_HD_NV FOREIGN KEY (ID_NV) REFERENCES NHAN_VIEN(ID_NV),
    CONSTRAINT FK_HD_KH FOREIGN KEY (ID_KH) REFERENCES KHACH_HANG(ID_KH),
    CONSTRAINT FK_HD_CA FOREIGN KEY (MA_CA) REFERENCES CA_LAM(MA_CA)
);

CREATE TABLE CTHD (
    MA_CTHD  VARCHAR(10) PRIMARY KEY,
    SO_LUONG INT CHECK (SO_LUONG > 0),
    GIA      DECIMAL(18,2),
    MA_HD    VARCHAR(10),
    MA_HH    VARCHAR(10),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD),
    CONSTRAINT FK_CTHD_HH FOREIGN KEY (MA_HH) REFERENCES HANG_HOA(MA_HH)
);

CREATE TABLE BO_HANG (
    MA_BO    VARCHAR(10) PRIMARY KEY,
    TEN      NVARCHAR(100),
    SO_LUONG INT,
    TONG_GIA DECIMAL(18,2),
    NGAY_BO  DATE,
    MA_HH    VARCHAR(10),
    CONSTRAINT FK_BO_HH FOREIGN KEY (MA_HH) REFERENCES HANG_HOA(MA_HH)
);

CREATE TABLE HANG_NHAP (
    MA_NHAP_HANG VARCHAR(10) PRIMARY KEY,
    SO_LUONG     INT,
    NGAY_NHAP    DATE,
    DON_GIA      DECIMAL(18,2),
    MA_NCC       VARCHAR(10),
    MA_HH        VARCHAR(10),
    CONSTRAINT FK_NHAP_NCC FOREIGN KEY (MA_NCC) REFERENCES NHA_CUNG_CAP(MA_NCC),
    CONSTRAINT FK_NHAP_HH  FOREIGN KEY (MA_HH)  REFERENCES HANG_HOA(MA_HH)
);
GO