
-- 4. CÁC CÂU LỆNH TRUY VẤN DỮ LIỆU

-------------------------------------------------------

-- ===================== 4.1. TRUY VẤN CƠ BẢN =====================

-- Q01: Liệt kê tất cả hàng hóa có giá từ 10 triệu đến 30 triệu

SELECT MA_HH, TEN_HH, GIA, LOAI_HH
FROM HANG_HOA
WHERE GIA BETWEEN 10000000 AND 30000000
ORDER BY GIA;

GO

-- Q02: Tìm hàng hóa có tên chứa từ 'Samsung'

SELECT MA_HH, TEN_HH, GIA, SO_LUONG
FROM HANG_HOA
WHERE TEN_HH LIKE N'%Samsung%';

GO

-- Q03: Liệt kê nhân viên đang làm việc (có thông tin họ tên, chức vụ)

SELECT CN.TEN, NV.TRANG_THAI, CV.TEN_CV
FROM NHAN_VIEN NV
INNER JOIN CON_NGUOI CN ON NV.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON NV.MA_CV = CV.MA_CV
WHERE NV.TRANG_THAI = N'Đang làm việc';

GO

-- Q04: Liệt kê tất cả khách hàng cùng hạng thẻ, sắp xếp theo điểm giảm dần

SELECT CN.TEN, CN.SDT, KH.KHTT, KH.DIEM
FROM KHACH_HANG KH
INNER JOIN CON_NGUOI CN ON KH.ID_KH = CN.ID_CN
ORDER BY KH.DIEM DESC;

GO

-- ===================== 4.2. JOIN NHIỀU BẢNG =====================

-- Q05: Chi tiết hóa đơn kèm tên nhân viên, tên khách hàng, ca làm

SELECT
  HD.MA_HD,
  NV_CN.TEN AS NHAN_VIEN,
  KH_CN.TEN AS KHACH_HANG,
  CL.THOI_GIAN AS CA,
  CL.NGAY,
  HD.TONG_TIEN
FROM HOA_DON HD
INNER JOIN CON_NGUOI NV_CN ON HD.ID_NV = NV_CN.ID_CN
INNER JOIN CON_NGUOI KH_CN ON HD.ID_KH = KH_CN.ID_CN
INNER JOIN CA_LAM CL ON HD.MA_CA = CL.MA_CA
ORDER BY HD.THOI_GIAN;

GO

-- Q06: Chi tiết từng dòng hóa đơn gồm tên hàng, số lượng, đơn giá, thành tiền

SELECT
  CT.MA_CTHD,
  HD.MA_HD,
  HH.TEN_HH,
  CT.SO_LUONG,
  CT.GIA AS DON_GIA,
  CT.SO_LUONG * CT.GIA AS THANH_TIEN
FROM CTHD CT
INNER JOIN HOA_DON HD ON CT.MA_HD = HD.MA_HD
INNER JOIN HANG_HOA HH ON CT.MA_HH = HH.MA_HH
ORDER BY HD.MA_HD, CT.MA_CTHD;

GO

-- Q07: Lịch chấm công chi tiết: Nhân viên – Ca – Ngày

SELECT
  CN.TEN,
  CV.TEN_CV,
  CL.THOI_GIAN AS CA,
  CL.NGAY
FROM CHAM_CONG CC
INNER JOIN NHAN_VIEN NV ON CC.ID_NV = NV.ID_NV
INNER JOIN CON_NGUOI CN ON NV.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON NV.MA_CV = CV.MA_CV
INNER JOIN CA_LAM CL ON CC.MA_CA = CL.MA_CA
ORDER BY CL.NGAY, CL.THOI_GIAN, CN.TEN;

GO

-- Q08: Thông tin nhập hàng chi tiết: Hàng hóa – Nhà cung cấp – Đơn giá nhập

SELECT
  HN.MA_NHAP_HANG,
  HH.TEN_HH,
  NCC.TEN AS NHA_CUNG_CAP,
  HN.SO_LUONG,
  HN.DON_GIA,
  HN.SO_LUONG * HN.DON_GIA AS TONG_GIA_NHAP,
  HN.NGAY_NHAP
FROM HANG_NHAP HN
INNER JOIN HANG_HOA HH ON HN.MA_HH = HH.MA_HH
INNER JOIN NHA_CUNG_CAP NCC ON HN.MA_NCC = NCC.MA_NCC
ORDER BY HN.NGAY_NHAP;

GO

-- ===================== 4.3. GROUP BY & HAVING =====================

-- Q09: Doanh thu theo từng ngày

SELECT
  CAST(HD.THOI_GIAN AS DATE) AS NGAY,
  COUNT(*) AS SO_HOA_DON,
  SUM(HD.TONG_TIEN) AS DOANH_THU
FROM HOA_DON HD
GROUP BY CAST(HD.THOI_GIAN AS DATE)
ORDER BY NGAY;

GO

-- Q10: Doanh thu theo từng nhân viên bán hàng

SELECT
  CN.TEN AS NHAN_VIEN,
  COUNT(HD.MA_HD) AS SO_DON,
  SUM(HD.TONG_TIEN) AS TONG_DOANH_THU
FROM HOA_DON HD
INNER JOIN CON_NGUOI CN ON HD.ID_NV = CN.ID_CN
GROUP BY CN.TEN
ORDER BY TONG_DOANH_THU DESC;

GO

-- Q11: Số lượng hàng hóa theo từng loại

SELECT
  LOAI_HH,
  COUNT(*) AS SO_SAN_PHAM,
  SUM(SO_LUONG) AS TONG_TON_KHO,
  MIN(GIA) AS GIA_THAP_NHAT,
  MAX(GIA) AS GIA_CAO_NHAT,
  AVG(GIA) AS GIA_TRUNG_BINH
FROM HANG_HOA
GROUP BY LOAI_HH
ORDER BY TONG_TON_KHO DESC;

GO

-- Q12: Nhà cung cấp có tổng giá trị nhập hàng > 200 triệu

SELECT
  NCC.TEN,
  COUNT(HN.MA_NHAP_HANG) AS SO_DON_NHAP,
  SUM(HN.SO_LUONG * HN.DON_GIA) AS TONG_GIA_TRI_NHAP
FROM HANG_NHAP HN
INNER JOIN NHA_CUNG_CAP NCC ON HN.MA_NCC = NCC.MA_NCC
GROUP BY NCC.TEN
HAVING SUM(HN.SO_LUONG * HN.DON_GIA) > 200000000
ORDER BY TONG_GIA_TRI_NHAP DESC;

GO

-- Q13: Số ca làm thực tế của từng nhân viên (từ bảng CHAM_CONG)

SELECT
  CN.TEN,
  COUNT(CC.MA_CA) AS SO_CA_THUC_TE
FROM CHAM_CONG CC
INNER JOIN CON_NGUOI CN ON CC.ID_NV = CN.ID_CN
GROUP BY CN.TEN
ORDER BY SO_CA_THUC_TE DESC;

GO

-- Q14: Khách hàng có tổng chi tiêu > 30 triệu

SELECT
  CN.TEN AS KHACH_HANG,
  KH.KHTT AS HANG_THE,
  COUNT(HD.MA_HD) AS SO_DON,
  SUM(HD.TONG_TIEN) AS TONG_CHI_TIEU
FROM HOA_DON HD
INNER JOIN KHACH_HANG KH ON HD.ID_KH = KH.ID_KH
INNER JOIN CON_NGUOI CN ON KH.ID_KH = CN.ID_CN
GROUP BY CN.TEN, KH.KHTT
HAVING SUM(HD.TONG_TIEN) > 30000000
ORDER BY TONG_CHI_TIEU DESC;

GO

-- ===================== 4.4. SUBQUERY =====================

-- Q15: Hàng hóa có giá cao hơn giá trung bình của cùng loại

SELECT MA_HH, TEN_HH, GIA, LOAI_HH
FROM HANG_HOA HH1
WHERE GIA > (
  SELECT AVG(GIA) FROM HANG_HOA HH2
  WHERE HH2.LOAI_HH = HH1.LOAI_HH
)
ORDER BY LOAI_HH, GIA DESC;

GO

-- Q16: Nhân viên chưa lập hóa đơn nào

SELECT CN.TEN, CV.TEN_CV
FROM NHAN_VIEN NV
INNER JOIN CON_NGUOI CN ON NV.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON NV.MA_CV = CV.MA_CV
WHERE NV.ID_NV NOT IN (
  SELECT DISTINCT ID_NV FROM HOA_DON
)
AND NV.TRANG_THAI = N'Đang làm việc';

GO

-- Q17: Hàng hóa chưa từng được bán (không có trong CTHD)

SELECT MA_HH, TEN_HH, SO_LUONG, GIA
FROM HANG_HOA
WHERE MA_HH NOT IN (
  SELECT DISTINCT MA_HH FROM CTHD
)
ORDER BY GIA DESC;

GO

-- Q18: Hóa đơn có tổng tiền cao nhất

SELECT TOP 1
  HD.MA_HD,
  NV_CN.TEN AS NHAN_VIEN,
  KH_CN.TEN AS KHACH_HANG,
  HD.TONG_TIEN,
  HD.THOI_GIAN
FROM HOA_DON HD
INNER JOIN CON_NGUOI NV_CN ON HD.ID_NV = NV_CN.ID_CN
INNER JOIN CON_NGUOI KH_CN ON HD.ID_KH = KH_CN.ID_CN
ORDER BY HD.TONG_TIEN DESC;

GO

-- ===================== 4.5. EXISTS =====================

-- Q19: Nhà cung cấp có ít nhất 1 mặt hàng bị bỏ

SELECT NCC.MA_NCC, NCC.TEN, NCC.SDT
FROM NHA_CUNG_CAP NCC
WHERE EXISTS (
  SELECT 1 FROM BO_HANG BH
  INNER JOIN HANG_HOA HH ON BH.MA_HH = HH.MA_HH
  WHERE HH.MA_NCC = NCC.MA_NCC
);

GO

-- Q20: Khách hàng đã từng mua hàng Tivi

SELECT DISTINCT CN.TEN, KH.KHTT
FROM KHACH_HANG KH
INNER JOIN CON_NGUOI CN ON KH.ID_KH = CN.ID_CN
WHERE EXISTS (
  SELECT 1 FROM HOA_DON HD
  INNER JOIN CTHD CT ON HD.MA_HD = CT.MA_HD
  INNER JOIN HANG_HOA HH ON CT.MA_HH = HH.MA_HH
  WHERE HD.ID_KH = KH.ID_KH AND HH.LOAI_HH = N'Tivi'
);

GO

-- ===================== 4.6. CASE WHEN =====================

-- Q21: Phân loại hàng hóa theo tầm giá

SELECT
  MA_HH,
  TEN_HH,
  GIA,
  CASE
    WHEN GIA < 2000000 THEN N'Giá rẻ'
    WHEN GIA BETWEEN 2000000 AND 15000000 THEN N'Tầm trung'
    WHEN GIA BETWEEN 15000001 AND 40000000 THEN N'Cao cấp'
    ELSE N'Siêu cao cấp'
  END AS PHAN_KHUC
FROM HANG_HOA
ORDER BY GIA;

GO

-- Q22: Tính lương thực nhận cho từng nhân viên

SELECT
  CN.TEN,
  CV.TEN_CV,
  CV.LUONG_CO_BAN AS LUONG_MOI_CA,
  L.SO_CA_LAM,
  L.THUONG,
  (CV.LUONG_CO_BAN * L.SO_CA_LAM + L.THUONG) AS LUONG_THUC_NHAN,
  CASE
    WHEN (CV.LUONG_CO_BAN * L.SO_CA_LAM + L.THUONG) >= 15000000 THEN N'Mức cao'
    WHEN (CV.LUONG_CO_BAN * L.SO_CA_LAM + L.THUONG) >= 10000000 THEN N'Mức trung'
    ELSE N'Mức thấp'
  END AS MUC_LUONG
FROM LUONG L
INNER JOIN CON_NGUOI CN ON L.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON L.MA_CV = CV.MA_CV
ORDER BY LUONG_THUC_NHAN DESC;

GO

-- ===================== 4.7. LEFT JOIN =====================

-- Q23: Tất cả hàng hóa và thông tin bỏ hàng (nếu có)

SELECT
  HH.MA_HH,
  HH.TEN_HH,
  HH.SO_LUONG AS TON_KHO,
  BH.TEN AS LY_DO_BO,
  BH.SO_LUONG AS SO_LUONG_BO,
  BH.NGAY_BO
FROM HANG_HOA HH
LEFT JOIN BO_HANG BH ON HH.MA_HH = BH.MA_HH
ORDER BY BH.NGAY_BO DESC;

GO

-- Q24: Tất cả nhân viên và số hóa đơn đã lập (kể cả NV chưa lập đơn nào)

SELECT
  CN.TEN,
  NV.TRANG_THAI,
  COUNT(HD.MA_HD) AS SO_HOA_DON
FROM NHAN_VIEN NV
INNER JOIN CON_NGUOI CN ON NV.ID_NV = CN.ID_CN
LEFT JOIN HOA_DON HD ON NV.ID_NV = HD.ID_NV
GROUP BY CN.TEN, NV.TRANG_THAI
ORDER BY SO_HOA_DON DESC;

GO

-- ===================== 4.8. UNION =====================

-- Q25: Danh sách tất cả người (NV + KH) cùng vai trò

SELECT CN.TEN, CN.SDT, N'Nhân viên' AS VAI_TRO
FROM NHAN_VIEN NV
INNER JOIN CON_NGUOI CN ON NV.ID_NV = CN.ID_CN

UNION ALL

SELECT CN.TEN, CN.SDT, N'Khách hàng' AS VAI_TRO
FROM KHACH_HANG KH
INNER JOIN CON_NGUOI CN ON KH.ID_KH = CN.ID_CN
ORDER BY VAI_TRO, TEN;

GO

-- ===================== 4.9. CTE (Common Table Expression) =====================

-- Q26: Top 5 sản phẩm bán chạy nhất (theo tổng số lượng bán)

;WITH SanPhamBanChay AS (
  SELECT
    CT.MA_HH,
    HH.TEN_HH,
    HH.LOAI_HH,
    SUM(CT.SO_LUONG) AS TONG_BAN,
    SUM(CT.SO_LUONG * CT.GIA) AS DOANH_THU
  FROM CTHD CT
  INNER JOIN HANG_HOA HH ON CT.MA_HH = HH.MA_HH
  GROUP BY CT.MA_HH, HH.TEN_HH, HH.LOAI_HH
)
SELECT TOP 5 * FROM SanPhamBanChay
ORDER BY TONG_BAN DESC;

GO

-- Q27: Lợi nhuận ước tính = Giá bán - Giá nhập (cho sản phẩm đã bán và có đơn nhập)

;WITH LoiNhuan AS (
  SELECT
    HH.MA_HH,
    HH.TEN_HH,
    CT.GIA AS GIA_BAN,
    HN.DON_GIA AS GIA_NHAP,
    CT.SO_LUONG AS SL_BAN,
    (CT.GIA - HN.DON_GIA) * CT.SO_LUONG AS LOI_NHUAN
  FROM CTHD CT
  INNER JOIN HANG_HOA HH ON CT.MA_HH = HH.MA_HH
  INNER JOIN HANG_NHAP HN ON CT.MA_HH = HN.MA_HH
)
SELECT * FROM LoiNhuan
ORDER BY LOI_NHUAN DESC;

GO

-- ===================== 4.10. VIEW =====================

-- Q28: View tổng quan doanh thu theo ngày

CREATE VIEW vw_DoanhThuTheoNgay AS
SELECT
  CAST(HD.THOI_GIAN AS DATE) AS NGAY,
  COUNT(*) AS SO_HOA_DON,
  SUM(HD.TONG_TIEN) AS DOANH_THU,
  AVG(HD.TONG_TIEN) AS TRUNG_BINH_DON
FROM HOA_DON HD
GROUP BY CAST(HD.THOI_GIAN AS DATE);

GO

SELECT * FROM vw_DoanhThuTheoNgay ORDER BY NGAY;

GO

-- Q29: View bảng lương chi tiết

CREATE VIEW vw_BangLuongChiTiet AS
SELECT
  CN.TEN,
  CV.TEN_CV,
  CV.LUONG_CO_BAN,
  L.SO_CA_LAM,
  L.THUONG,
  (CV.LUONG_CO_BAN * L.SO_CA_LAM + L.THUONG) AS LUONG_THUC_NHAN
FROM LUONG L
INNER JOIN CON_NGUOI CN ON L.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON L.MA_CV = CV.MA_CV;

GO

SELECT * FROM vw_BangLuongChiTiet ORDER BY LUONG_THUC_NHAN DESC;

GO

-- ===================== 4.11. TRUY VẤN NÂNG CAO =====================

-- Q30: Hàng hóa sắp hết hạn sử dụng (trong 30 ngày tới)

SELECT MA_HH, TEN_HH, SO_LUONG, HAN_SU_DUNG,
  DATEDIFF(DAY, GETDATE(), HAN_SU_DUNG) AS CON_LAI_NGAY
FROM HANG_HOA
WHERE DATEDIFF(DAY, GETDATE(), HAN_SU_DUNG) <= 30
  AND DATEDIFF(DAY, GETDATE(), HAN_SU_DUNG) >= 0
ORDER BY HAN_SU_DUNG;

GO

-- Q31: Bảng tổng hợp tồn kho – nhập – bán – bỏ theo từng mặt hàng

SELECT
  HH.MA_HH,
  HH.TEN_HH,
  HH.SO_LUONG AS TON_KHO,
  ISNULL(NHAP.TONG_NHAP, 0) AS DA_NHAP,
  ISNULL(BAN.TONG_BAN, 0)  AS DA_BAN,
  ISNULL(BO.TONG_BO, 0)    AS DA_BO
FROM HANG_HOA HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_NHAP FROM HANG_NHAP GROUP BY MA_HH
) NHAP ON HH.MA_HH = NHAP.MA_HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_BAN FROM CTHD GROUP BY MA_HH
) BAN ON HH.MA_HH = BAN.MA_HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_BO FROM BO_HANG GROUP BY MA_HH
) BO ON HH.MA_HH = BO.MA_HH
ORDER BY HH.MA_HH;

GO

-- ===================== 4.12. TRUY VẤN KIỂM CHỨNG TRIGGER =====================

-- Q33: Kiểm chứng hạng khách hàng khớp với điểm tích lũy
-- (Xác minh TRG05 và TRG06 hoạt động đúng)

SELECT
  CN.TEN,
  KH.KHTT AS HANG_THE_HIEN_TAI,
  KH.DIEM,
  CASE
    WHEN KH.DIEM >= 5000 THEN N'Kim cương'
    WHEN KH.DIEM >= 1500 THEN N'Vàng'
    WHEN KH.DIEM >= 500  THEN N'Bạc'
    ELSE N'Thân thiết'
  END AS HANG_THE_TINH_TOAN,
  COUNT(HD.MA_HD) AS SO_HOA_DON_MUA,
  SUM(HD.TONG_TIEN) AS TONG_CHI_TIEU,
  FLOOR(SUM(HD.TONG_TIEN) / 100000) AS DIEM_THEO_CHI_TIEU
FROM KHACH_HANG KH
INNER JOIN CON_NGUOI CN ON KH.ID_KH = CN.ID_CN
LEFT JOIN HOA_DON HD ON KH.ID_KH = HD.ID_KH
GROUP BY CN.TEN, KH.KHTT, KH.DIEM
ORDER BY TONG_CHI_TIEU DESC;

GO

-- Q34: Kiểm chứng tồn kho: So sánh tồn kho hiện tại vs tính toán từ nhập/bán/bỏ
-- (Xác minh TRG02, TRG03, TRG04 hoạt động đúng)

SELECT
  HH.MA_HH,
  HH.TEN_HH,
  HH.SO_LUONG AS TON_KHO_HIEN_TAI,
  ISNULL(NHAP.TONG_NHAP, 0) AS TONG_NHAP,
  ISNULL(BAN.TONG_BAN, 0) AS TONG_BAN,
  ISNULL(BO.TONG_BO, 0) AS TONG_BO,
  ISNULL(NHAP.TONG_NHAP, 0) - ISNULL(BAN.TONG_BAN, 0) - ISNULL(BO.TONG_BO, 0) AS TON_KHO_TINH_TOAN,
  CASE
    WHEN HH.SO_LUONG = (ISNULL(NHAP.TONG_NHAP, 0) - ISNULL(BAN.TONG_BAN, 0) - ISNULL(BO.TONG_BO, 0))
    THEN N'✓ Khớp'
    ELSE N'✗ Sai lệch'
  END AS KIEM_CHUNG
FROM HANG_HOA HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_NHAP FROM HANG_NHAP GROUP BY MA_HH
) NHAP ON HH.MA_HH = NHAP.MA_HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_BAN FROM CTHD GROUP BY MA_HH
) BAN ON HH.MA_HH = BAN.MA_HH
LEFT JOIN (
  SELECT MA_HH, SUM(SO_LUONG) AS TONG_BO FROM BO_HANG GROUP BY MA_HH
) BO ON HH.MA_HH = BO.MA_HH
ORDER BY HH.MA_HH;

GO

-- Q35: Kiểm chứng số ca làm: So sánh SO_CA_LAM trong LUONG vs thực tế từ CHAM_CONG
-- (Xác minh TRG07 hoạt động đúng)

SELECT
  CN.TEN,
  CV.TEN_CV,
  L.SO_CA_LAM AS CA_LAM_TRONG_LUONG,
  COUNT(CC.MA_CA) AS CA_LAM_THUC_TE,
  CASE
    WHEN L.SO_CA_LAM = COUNT(CC.MA_CA)
    THEN N'✓ Khớp'
    ELSE N'✗ Sai lệch'
  END AS KIEM_CHUNG
FROM LUONG L
INNER JOIN CON_NGUOI CN ON L.ID_NV = CN.ID_CN
INNER JOIN CHUC_VU CV ON L.MA_CV = CV.MA_CV
LEFT JOIN CHAM_CONG CC ON L.ID_NV = CC.ID_NV
GROUP BY CN.TEN, CV.TEN_CV, L.SO_CA_LAM
ORDER BY CN.TEN;

GO

-------------------------------------------------------